"use client"
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Nav from '@/components/navBar/page'
import Footer from "@/components/footer/page";
import { usePathname } from "next/navigation";
import { SessionProvider } from "next-auth/react";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

 const metadata: Metadata = {
  title: "Clinica Origen",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const pathname = usePathname();

  const hideNavAndFooter = pathname.startsWith("/pages/protected");
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
         <SessionProvider>
        {!hideNavAndFooter && <Nav />}
       {children}
        {!hideNavAndFooter && <Footer />}
        </SessionProvider>
      </body>
    </html>
  );
}